apiVersion : apps/v1
kind: Deployment
metadata:
  name: dashcccpipelinesjavascriptdocker 
  labels:
    app: test-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-pipeline
  template:
    metadata:
      labels:
        app: test-pipeline 
    spec:
      containers:
        - name: dashcccpipelinesjavascriptdocker 
          image: mycontainerregistry2testdashpipelines.azurecr.io/dashcccpipelinesjavascriptdocker
          ports:
          - containerPort: 8080
